### ISSUE TITLE
TypeError: tar.Extract is not a function

### ISSUE THREAD

**Issue by aelbore** [sonatype/bower-nexus3-resolver#25] opened 2019-04-16 02:24 UTC
Stack trace:
TypeError: tar.Extract is not a function

**Comment by hicom150** [comment] 2019-04-16 06:52
Duplicate of #23

**Comment by joedragons** [comment] 2019-04-16 17:46
Created https://github.com/sonatype/bower-nexus3-resolver/pull/26 to fix this, going to merge now.

**Closed by joedragons** 2019-04-16 17:46 UTC
